# Generated by Django 5.2.12 on 2026-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0356_add_course_editor_update_bulk_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(
                default=False,
                help_text='This field signifies if this course is in the B2C subscription catalog',
            ),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(
                default=False,
                help_text='This field signifies if this course is in the B2C subscription catalog',
            ),
        ),
    ]
