# Generated by Django 5.2.12 on 2026-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0358_course_b2c_subscription_inclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='This field signifie if this course is in the B2C subscription catalog'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='This field signifie if this course is in the B2C subscription catalog'),
        ),
    ]
