# Generated by Django 5.2.12 on 2026-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0359_course_b2c_subscription_inclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='Signifies whether this program is included in the B2C subscription catalog.'),
        ),
        migrations.AddField(
            model_name='program',
            name='b2c_subscription_inclusion',
            field=models.BooleanField(blank=True, default=False, help_text='Signifies whether this program is included in the B2C subscription catalog.'),
        ),
    ]
