# Generated by Django 5.2.12 on 2026-07-23 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0360_historicalprogram_b2c_subscription_inclusion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bulkoperationtask',
            index=models.Index(fields=['-created'], name='cm_bo_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperationtask',
            index=models.Index(fields=['status', '-created'], name='cm_bo_task_status_created_idx'),
        ),
    ]
